# Generated by Django 5.1 on 2025-11-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0003_remove_property_image_remove_property_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('properties.agentprofile',),
        ),
    ]
