# Generated by Django 5.1 on 2025-11-12 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_mediaproperty_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video',
        ),
        migrations.AlterField(
            model_name='mediaproperty',
            name='Images',
            field=models.ImageField(null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='mediaproperty',
            name='caption',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='mediaproperty',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MediaProperty', to='properties.property'),
        ),
    ]
